In [1]:
import torch


x = torch.tensor([3,4,5])
y = torch.tensor([6,7,8])



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/zhihu/miniconda3/envs/l1d-py311/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/zhihu/miniconda3/envs/l1d-py311/lib/python3.11/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/zhihu/miniconda3/envs/l1d-py311/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 739, in st

In [2]:
a = torch.arange(12).reshape(3,4)

In [3]:
a.T


tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [4]:
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
b = a.clone()
b

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
a*b

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]])

In [8]:
x = torch.tensor([0,1,2], dtype=torch.float32)
y = torch.ones(3, dtype=torch.float32)
x, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor(3.))

In [9]:
torch.sum(x * y)

tensor(3.)

In [13]:
x = torch.arange(12,dtype=torch.float32).reshape(3,4)
y = torch.arange(12,dtype=torch.float32).reshape(4,3)
torch.mm(x,y)

tensor([[ 42.,  48.,  54.],
        [114., 136., 158.],
        [186., 224., 262.]])

In [14]:
u = torch.tensor([3,4], dtype=torch.float32)
torch.norm(u)

tensor(5.)