In [1]:
import torch

y = torch.arange(6, dtype=torch.float32)

In [2]:
y.shape()

TypeError: 'torch.Size' object is not callable

In [3]:
y.shape

torch.Size([6])

In [4]:
y.reshape(2,3)

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [5]:
y.shape

torch.Size([6])

In [6]:
z = torch.zeros(2,3,4)

In [7]:
print(z)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [8]:
a = torch.ones(2,3,4)
print(a)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [9]:
b = torch.rand(2,3,4)
print(b)

tensor([[[0.6366, 0.9816, 0.5433, 0.3340],
         [0.4553, 0.7400, 0.6358, 0.4532],
         [0.6686, 0.2727, 0.8564, 0.6314]],

        [[0.9110, 0.4371, 0.5701, 0.3261],
         [0.8301, 0.9774, 0.5710, 0.1858],
         [0.9464, 0.8802, 0.5490, 0.2080]]])


In [10]:
c = torch.randn(2,3,4)
print(c)

tensor([[[ 0.5468, -0.7259, -0.5765, -0.7000],
         [-0.4505, -0.9540,  0.1139, -0.9341],
         [-0.7564,  1.0761, -1.7290,  0.1994]],

        [[ 0.5492,  0.9775, -0.0761,  0.8224],
         [ 1.1992,  1.7150, -1.0172, -0.2810],
         [ 1.0708,  0.5619,  2.0117, -0.1117]]])


In [11]:
d = torch.tensor([[1,2,3], [4, 5, 6], [7, 8, 9]])

In [12]:
print(d)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [13]:
print(y[-1])

tensor(5.)


In [14]:
print(y[1:3])

tensor([1., 2.])


In [20]:
print(y.reshape(2,3)[1, 2])

tensor(5.)


In [21]:
print(torch.exp(y))

tensor([  1.0000,   2.7183,   7.3891,  20.0855,  54.5982, 148.4132])


In [22]:
i = torch.tensor([1,2,3])
j = torch.tensor([4,5,6])
print(i+j)
print(i*j)

tensor([5, 7, 9])
tensor([ 4, 10, 18])


In [23]:
print(i**j)

tensor([  1,  32, 729])


In [24]:
i = torch.arange(12, dtype=torch.float32).reshape(3, 4)
j = torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]], dtype=torch.float32)
print(torch.cat((i, j), dim=0))
print(torch.cat((i, j), dim=1))


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
        [ 4.,  5.,  6.,  7.,  5.,  6.,  7.,  8.],
        [ 8.,  9., 10., 11.,  9., 10., 11., 12.]])


In [25]:
print(i == j)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [26]:
print(i.sum())

tensor(66.)


In [27]:
i.sum()

tensor(66.)

In [28]:
a = torch.arange(3, dtype=torch.float32).reshape(3, 1)
b = torch.arange(2, dtype=torch.float32).reshape(1, 2)

In [29]:
a,b

(tensor([[0.],
         [1.],
         [2.]]),
 tensor([[0., 1.]]))

In [30]:
a+b

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

In [32]:
add1 = id(a)
a = a + b
add2 = id(a)
add1, add2

(4581887920, 4581886960)

In [33]:
X = a.numpy()
Y = torch.from_numpy(X)
type(X), type(Y)



(numpy.ndarray, torch.Tensor)

In [34]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

TypeError: '>' not supported between instances of 'numpy.ndarray' and 'Tensor'

In [36]:
a == b, a > b, a < b

(tensor([[False, False]]), tensor([[True, True]]), tensor([[False, False]]))

In [ ]:
a = torch.arange()