In [1]:
import torch

y = torch.arange(6, dtype=torch.float32)

In [2]:
y.shape()

TypeError: 'torch.Size' object is not callable

In [3]:
y.shape

torch.Size([6])

In [4]:
y.reshape(2,3)

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [5]:
y.shape

torch.Size([6])

In [6]:
z = torch.zeros(2,3,4)

In [7]:
print(z)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [8]:
a = torch.ones(2,3,4)
print(a)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [9]:
b = torch.rand(2,3,4)
print(b)

tensor([[[0.6366, 0.9816, 0.5433, 0.3340],
         [0.4553, 0.7400, 0.6358, 0.4532],
         [0.6686, 0.2727, 0.8564, 0.6314]],

        [[0.9110, 0.4371, 0.5701, 0.3261],
         [0.8301, 0.9774, 0.5710, 0.1858],
         [0.9464, 0.8802, 0.5490, 0.2080]]])


In [10]:
c = torch.randn(2,3,4)
print(c)

tensor([[[ 0.5468, -0.7259, -0.5765, -0.7000],
         [-0.4505, -0.9540,  0.1139, -0.9341],
         [-0.7564,  1.0761, -1.7290,  0.1994]],

        [[ 0.5492,  0.9775, -0.0761,  0.8224],
         [ 1.1992,  1.7150, -1.0172, -0.2810],
         [ 1.0708,  0.5619,  2.0117, -0.1117]]])
