In [7]:
import torch


x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [9]:
x.requires_grad_(True)
x.grad

In [10]:


y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [11]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [12]:
x.grad == 4 * x

tensor([True, True, True, True])